### ISSUE TITLE
`use_query` does not properly pre-fetch some model fields

### ISSUE THREAD

**Issue by Archmonger** [idom-team/django-idom#110]
### Current Situation

`ManyToMany` fields are not properly prefetched, thus causing `SynchronousOnlyOperation` exceptions.

For example, in [this case](https://github.com/Archmonger/Conreq/blob/ffd3601e6b961eca18caf10b3fde73539aab304a/conreq/_core/app_store/models.py#L116).

### Proposed Actions

Determine why the current prefetch logic doesn't work on this use case.

**Comment by rmorshea** [comment]
It looks like [one-to-many](https://github.com/django/django/blob/67da22f08e05018ea968fcacbac9ac37ea925d85/django/db/models/fields/related_descriptors.py#L640) and [many-to-many](https://github.com/django/django/blob/67da22f08e05018ea968fcacbac9ac37ea925d85/django/db/models/fields/related_descriptors.py#L986) relationships return relationship managers. Should be as simple as calling the `get_queryset()` and recursively resolving values.

**Comment by rmorshea** [comment]
Ok, as discovered in that draft PR, `get_queryset()` does not actually cache anything. After doing a bit of research, it seems like this is something that needs to be managed by users with [`prefetch_related`](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#prefetch-related) or [`select_related`](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#select-related). There's a [`prefect_related_objects`](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#django.db.models.prefetch_related_objects) function that can work on model instances rather than queries, but I'm not really sure how that could be used automatically.
